profiler:
  url: https://arc.notom3ga.me/
  config:
    additional-files: []
    hidden-tokens:
      - seed
      - server-ip
      - rcon
      - query
      - database
      - settings.bungeecord-addresses
      - settings.velocity-support.secret
      - token
