profiler:
  urls:
    profiler: https://arc.notom3ga.me/
    bytebin: https://bytebin.lucko.me/
  graph:
    interval: 40
    data:
      mspt: true
      tps: true
      players: true
      entities: true
      chunks: true
      block-entites: true
      process-cpu: true
      system-cpu: true
      memory: true
  config:
    additional-files: []
    hidden-tokens:
      - seed
      - server-ip
      - rcon
      - query
      - database
      - settings.bungeecord-addresses
      - settings.velocity-support.secret
      - token
